"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.samplePageTemplate = void 0;
exports.samplePageTemplate = "\nimport { Metadata } from \"next\";\n\nexport const metadata: Metadata = {\n  title: \"__COMPONENT_NAME__ Page\",\n  description: \"This is a sample page generated by generator\",\n};\n\nexport default function __COMPONENT_NAME__() {\n  return (\n    <main className=\"p-6\">\n      <h1>Hello from __COMPONENT_NAME__ \uD83D\uDC4B</h1>\n      <p>This page uses App Router metadata for SEO.</p>\n    </main>\n  );\n}\n";
